name: Main Branch Trigger

on:
  push:
    branches: 
      - master
    paths: 
      - 'src/**'
      - '.github/workflows/main-branch-trigger.yml'

jobs:
  call-update-translation-workflow:
    name: Update Translation Wiki Pages
    uses: ./.github/workflows/jobs/update-translation.yml
  call-build-workflow:
    name: Build
    uses: ./.github/workflows/jobs/build.yml