name: Release Branch Trigger

on: create

jobs:
  call-build-workflow:
    name: Build
    if: ${{ contains(github.ref, 'refs/heads/releases/') }}
    uses: ./.github/workflows/jobs/build.yml
  call-release-workflow:
    name: Release
    needs: call-build-workflow
    if: ${{ contains(github.ref, 'refs/heads/releases/') }}
    uses: ./.github/workflows/jobs/release.yml