name: Release

on: workflow_call

jobs:
  release:
    runs-on: [windows-latest]
    steps:
    - name: Test
      run: |
        # what
        ls
      shell: pwsh
    # - name: Create Release
    #   id: create_release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: ${{ github.ref }}
    #     release_name: Release ${{ github.ref }}
    #     body: |
    #       ### Patch Notes

    #       **[New]** Item
    #       **[Fix]** Item
    #       **[Enhancement]** Item
    #     draft: true
    #     prerelease: false

    # - name: Upload Release Asset
    #   uses: actions/upload-release-asset@v1.0.1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: ./ReplayBook.zip
    #     asset_name: ReplayBook.zip
    #     asset_content_type: application/zip